### ISSUE TITLE
别下，捞钱的

### ISSUE THREAD

**Issue by andrewChen-a** [cymok/Document#2]
第一页就是购买链接，只放部分书，比要求关注公众号的还恶心

说什么整理不易，那为什么下完再说？不能写在github上？？

骗人就是骗人

**Comment by zjmok** [comment]
1.资料内容与本人完全无关，捞钱的是狗
2.没法理解 伸手拿资料了 还无法接受原作者加的部分推广信息。国产手机系统里有广告是不是就不能用了
